### ISSUE TITLE
Class registration process

### ISSUE THREAD

**Issue by kirubeltadesse** [Roberamelaek/Robera#3]
We need to get this task complete before moving to #4

**Comment by kirubeltadesse** [comment]
Hi Robe,

Yesterday, I forget to ask you about your high school registration process.
1. When are you starting class?
2. What is the registration process on ?
Please make sure to answer this questions down below!

**Comment by Roberamelaek** [comment]
# Description
Prince George's County Public Schools (PGCPS) is a school district located in Prince George's County, Maryland, United States. It is one of the largest and most diverse school districts in the state of Maryland. PGCPS serves students from pre-kindergarten through grade 12 and includes a wide range of educational programs and services. 

## High School name

Prince George's Country Public Schools

### Starting date

Starts at August 28

### What is the registration process

The registration process is with an appointment  at International Office at 8908 Riggs Road , Room 284 Hyattsville, MD 20783
Tel: 301-445-8460 

The required documents-

-Student Birth Certificate
-Guardian/Sponsor ID
-Student Immunization Record
-Lease Agreement or Mortgage statement with Guardian/Sponsor's Name
-Most Recent Transcripts

after the appointment they will notify you and tell you about the school that your going to

**Comment by kirubeltadesse** [comment]
Thank you for thoroughly explaining the situation you are in. I have a few questions.
1. Have you submitted all the required documents? if not, what is remaining
2. If you have submitted it, please let me know when you'll hear back. When will you submit all the required documents if you still need to submit them?

I believe Mom is your Guardian/Sponsor ID, and you should also have the mortgage statement from her. Have you brought your transcripts with you and your birth certificate?

Have you called or gone in person and spoken with the international officer? If not, when are you planning to do that?

**Comment by Roberamelaek** [comment]
### Have you submitted all the required documents? if not, what is remaining
No I currently have not submitted documents the remaining document is the Lease Agreement or Mortgage statement with Guardian/Sponsor's Name , and this week I talked to the house owner and scheduled for the document to be formed on august Saturday 29  and I am planing to call the PGCPS and schedule an appointment as soon I get the document  and I have a printed version of the transcript

**Comment by kirubeltadesse** [comment]
I didn't understand what you are trying to say on the previous note!

**August 29** is super late. You need to start class on August 28. You need to get the document ready either today or tomorrow. 

And submit it on Wednesday. Do you understand? You don't need to be behind classes since you are starting new from Ethiopia.

**Comment by Roberamelaek** [comment]
sorry on the previous note i meant 19 instead of 29 but he didn't show up and i tried to call him today but his phone isn't answering i will try calling him again and schedule the appointment for wednesday .

**Comment by Roberamelaek** [comment]
I got the lease agreement but mom will sign it first and make a copy , and give the original paper to the house

**Comment by kirubeltadesse** [comment]
Hey @Roberamelaek,

You need to get her signed that should not be a problem for you. Then you should take it to the school **TODAY** not tomorrow. Tomorrow people will be out of office. 

You need to finish this today because you are starting school on Monday. Tomorrow, you should prepare the stuff you need for class.

**Comment by kirubeltadesse** [comment]
Meeting with school office on **Sept. 01**

**Comment by kirubeltadesse** [comment]
@Roberamelaek, While waiting for this appointment you can start working on #4!

**Comment by Roberamelaek** [comment]
the meeting isnt on sept 08 its on sept 01

**Comment by kirubeltadesse** [comment]
Could you please write an update here?

**Comment by Roberamelaek** [comment]
I went to northwestern high-school to enroll at sept 5 but they said the lease agreement need to be notarized and there need to be 2 proof of residency so i talked to the land lord and scheduled to get a notarized lease and finding documents for proof of residency

**Comment by Roberamelaek** [comment]
# Its Done
 They told me that i could start tomorrow

## Requirement
- 1 proof of resedence the bank statement is approved but the drivers licence package did qualify because it didnt jave date on it so i have to provide 1 in the next 30 days while attending school
- 1 vacceine i gave them a scuduel date for vacceine but they will ask it after the vacceine appointment 

![Image](https://github.com/Roberamelaek/Robera/assets/69109461/5ecfc120-7cd5-47ff-9b5a-c6ca85caa814)

**Comment by kirubeltadesse** [comment]
You can move it to the done section 🎉
