### ISSUE TITLE
Summer internship/research application

### ISSUE THREAD

**Issue by kirubeltadesse** [Roberamelaek/Robera#4]
# Description

This ticket relates directly to #3 . After you have completed that one you can start on this one. 

Research for High School Summer application: 

- Companies
- Schools
- Organization (non-profits..)

Submit minimum of 3 links max 7 links of different opportunities that you can apply for Summer 2024 down below. 

## Acceptance

- You should readed the qualification and make sure you qualify 
- It should be during the summer time
- It shouldn't have no application fees
- It should be for high school students

**Comment by kirubeltadesse** [comment]
Please add all the links you have found ASAP?

**Comment by kirubeltadesse** [comment]
[Seek MentorShip](https://seek.nsbe.org/)

**Comment by Roberamelaek** [comment]
https://www.theladders.com/job-listing/2024-summer-software-engineer-intern-workiva-hyattsville-maryland-_v2_-11-3082827070.html

**Comment by kirubeltadesse** [comment]
> https://www.theladders.com/job-listing/2024-summer-software-engineer-intern-workiva-hyattsville-maryland-_v2_-11-3082827070.html

Hi Rebe, this looks like an email list for summer internship opportunities. We need the actual application pages 👍🏼

**Comment by Roberamelaek** [comment]
https://www.internshipskey.com/job/nasa-high-school-internship/

**Comment by Roberamelaek** [comment]
https://www.campusreel.org/student-jobs/university-of-maryland-smith-school-of-business/marketing-intern

**Comment by Roberamelaek** [comment]
> > https://www.theladders.com/job-listing/2024-summer-software-engineer-intern-workiva-hyattsville-maryland-_v2_-11-3082827070.html
> 
> Hi Rebe, this looks like an email list for summer internship opportunities. We need the actual application pages 👍🏼

https://boards.greenhouse.io/yext/jobs/5315129

**Comment by kirubeltadesse** [comment]
Hi Robe, 
Thank you for collecting the links. Could you please complete the table below?





| Internship Name             | Start Date   | End Date  | Application Link| Location |
| :----------------             | :----------: | :---------:  |:----------------|---------|
| Kci technologies |                   |                 | [Engineering intern link](https://careers-kci.icims.com/jobs/4738/engineering-intern/job?mode=job&iis=LinkedIn&iisn=LinkedIn&mobile=false&width=1074&height=500&bga=true&needsRedirect=false&jan1offset=-300&jun1offset=-240) | Washington, US |
| Boeing        |  |  | [Boeing Linkin](https://www.linkedin.com/jobs/view/boeing-boeing-summer-2024-internship-program-paid-business-operations-program-management-and-manufacturing-operations-application-via-wayup-at-wayup-3691827276/) | Germantown, MD |
| NVIDIA Ignite        |  |  | [Nvidia internship](https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite/job/US-CA-Santa-Clara/NVIDIA-Ignite-Internship--Hardware-Software-Business-Operations---Summer-2024_JR1972457?utm_source=CarbosJobs) | US, Remote |
|ABC News Race & Culture Intern|  |  | [Disney internship](https://www.internships.com/posting/lit_39566220504?utm_campaign=google_jobs_apply&utm_source=google_jobs_apply&utm_medium=organic) | Washington, DC |
| peraton        |  |  | [Peraton internship](https://careers-peraton.icims.com/jobs/137038/job?utm_source=indeed_integration&iis=Job+Board&iisn=Indeed&indeed-apply-token=73a2d2b2a8d6d5c0a62696875eaebd669103652d3f0c2cd5445d3e66b1592b0f&iis=HireClix&iisn=Indeed&mobile=false&width=1131&height=500&bga=true&needsRedirect=false&jan1offset=-300&jun1offset=-240) | Silver Spring, MD |
| Seek        |     |  | [Summer Engineering](https://seek.nsbe.org/) | |
| Microsoft        | July - 11 | August - 5 | [microsoft FAQ Page](https://careers.microsoft.com/v2/global/en/discoveryprogram) | |
 |Yext        |  |  | [Software Enginering](https://boards.greenhouse.io/yext/jobs/5315129) |Washington,DC |

**Comment by kirubeltadesse** [comment]
@Roberamelaek, nice pic. I like it. On the above table, you need to complete the application link column. In addition, `ZipRecruiter` can not be used here. It is not an internship name. Please complete this table as soon as possible.

**Comment by Roberamelaek** [comment]
> @Roberamelaek, nice pic. I like it. On the above table, you need to complete the application link column. In addition, `ZipRecruiter` can not be used here. It is not an internship name. Please complete this table as soon as possible. 

Ok i will get to it as soon as possible
